# @Author: chesterblue
# @File Name:gui.py

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

IconImg = "./img/logo.png"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 597)
        # 禁止最大化按钮
        MainWindow.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint|QtCore.Qt.WindowCloseButtonHint)
        # 禁止拉伸窗口大小
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height())
        # 设置窗口图标
        MainWindow.setWindowIcon(QtGui.QIcon(IconImg))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(11, 22, 771, 521))
        self.widget.setObjectName("widget")
        # 垂直布局
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        # 水平布局
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        # 顶部：lineEdit、label、spinBox、comboBox、button -------------start:top-----------------------------------
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setEditable(False)
        self.comboBox.setCurrentText("")
        self.comboBox.setIconSize(QtCore.QSize(16, 16))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setProperty("value", 5)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        # 第一层水平布局添加到总体的垂直布局中
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        # ---------------------------------------------------------end:top------------------------------------------
        # progressBar、checkBox、listView-------------------------start:middle---------------------------------------
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        # checkBox水平布局区域-----------------------------start-------------------------------
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_1 = QtWidgets.QCheckBox()
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontalLayout_2.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox()
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox()
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox()
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_2.addWidget(self.checkBox_4)
        # 四个checkBox的水平布局添加到和进度条组成的垂直布局中
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        # checkBox水平布局区域-----------------------------end-------------------------------
        # 两个listView水平布局区域--------------------------start--------------------------------
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.listView = QtWidgets.QListView(self.widget)
        self.listView.setObjectName("listView")
        self.horizontalLayout_1.addWidget(self.listView)
        self.listView_1 = QtWidgets.QListView(self.widget)
        self.listView_1.setObjectName("listView")
        self.horizontalLayout_1.addWidget(self.listView_1)
        # 两个listView水平布局区域--------------------------end--------------------------------
        # 两个水平分布的listView添加到和进度条组成的垂直布局中
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        # 进度条、listView添加到总体的垂直布局中
        self.verticalLayout_2.addLayout(self.verticalLayout)
        # ----------------------------------------end:middle----------------------------------------------------------
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionproxy = QtWidgets.QAction(MainWindow)
        self.actionproxy.setObjectName("actionproxy")
        self.actionAPI_Key = QtWidgets.QAction(MainWindow)
        self.actionAPI_Key.setObjectName("actionAPI_Key")
        self.menu.addAction(self.actionproxy)
        self.menu.addAction(self.actionAPI_Key)
        self.menubar.addAction(self.menu.menuAction())
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Subdomain lookup V1.5"))
        self.label.setText(_translate("MainWindow", "站点"))
        self.label_3.setText(_translate("MainWindow", "字典"))
        self.comboBox.setPlaceholderText(_translate("MainWindow", "common.txt"))
        self.label_2.setText(_translate("MainWindow", "线程"))
        self.pushButton.setText(_translate("MainWindow", "Start"))
        self.checkBox_1.setText(_translate("MainWindow", "Baidu"))
        self.checkBox_2.setText(_translate("MainWindow", "Bing"))
        self.checkBox_3.setText(_translate("MainWindow", "Google"))
        self.checkBox_4.setText(_translate("MainWindow", "DNS resolution"))
        self.menu.setTitle(_translate("MainWindow", "设置"))
        self.actionproxy.setText(_translate("MainWindow", "代理"))
        self.actionAPI_Key.setText(_translate("MainWindow", "API Key"))


class Ui_SetProxy(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(410, 296)
        # 禁止最大化按钮
        Dialog.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint | QtCore.Qt.WindowCloseButtonHint)
        # 禁止拉伸窗口大小
        Dialog.setFixedSize(Dialog.width(), Dialog.height())
        # 设置窗口图标
        Dialog.setWindowIcon(QtGui.QIcon(IconImg))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 351, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.https_port = QtWidgets.QSpinBox(self.layoutWidget)
        self.https_port.setMaximum(65535)
        self.https_port.setObjectName("https_port")
        self.gridLayout.addWidget(self.https_port, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.https_address = QtWidgets.QLineEdit(self.layoutWidget)
        self.https_address.setObjectName("https_address")
        self.gridLayout.addWidget(self.https_address, 2, 1, 1, 1)
        self.http_address = QtWidgets.QLineEdit(self.layoutWidget)
        self.http_address.setObjectName("http_address")
        self.gridLayout.addWidget(self.http_address, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.http_port = QtWidgets.QSpinBox(self.layoutWidget)
        self.http_port.setMaximum(65535)
        self.http_port.setObjectName("http_port")
        self.gridLayout.addWidget(self.http_port, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.testProxyButton = QtWidgets.QPushButton(Dialog)
        self.testProxyButton.setGeometry(QtCore.QRect(30, 160, 75, 23))
        self.testProxyButton.setObjectName("testProxyButton")

        # 设置tab顺序
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.http_address, self.http_port)
        Dialog.setTabOrder(self.http_port, self.https_address)
        Dialog.setTabOrder(self.https_address, self.https_port)
        Dialog.setTabOrder(self.https_port, self.testProxyButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "代理"))
        self.label_2.setText(_translate("Dialog", "HTTPS:"))
        self.label.setText(_translate("Dialog", "HTTP:"))
        self.label_4.setText(_translate("Dialog", "port"))
        self.label_3.setText(_translate("Dialog", "ip/domain name"))
        self.testProxyButton.setText(_translate("Dialog", "Test"))


class Ui_TestProxy(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(379, 160)
        # 禁止最大化按钮
        Dialog.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint | QtCore.Qt.WindowCloseButtonHint)
        # 禁止拉伸窗口大小
        Dialog.setFixedSize(Dialog.width(), Dialog.height())
        # 设置窗口图标
        Dialog.setWindowIcon(QtGui.QIcon(IconImg))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 120, 331, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 40, 321, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "测试代理"))
        self.label_2.setText(_translate("Dialog", "输入任意URL以检查代理"))
        self.label.setText(_translate("Dialog", "链接/URL"))
        self.lineEdit.setText(_translate("Dialog", "http://"))


class Ui_SetAPI(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        # 禁止最大化按钮
        Dialog.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint | QtCore.Qt.WindowCloseButtonHint)
        # 禁止拉伸窗口大小
        Dialog.setFixedSize(Dialog.width(), Dialog.height())
        # 设置窗口图标
        Dialog.setWindowIcon(QtGui.QIcon(IconImg))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(50, 60, 301, 111))
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(10, 40, 281, 21))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.virus_api_key_value = QtWidgets.QLineEdit(self.widget)
        self.virus_api_key_value.setObjectName("virus_api_key_value")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.virus_api_key_value)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "API Key"))
        self.groupBox.setTitle(_translate("Dialog", "API Key"))
        self.label.setText(_translate("Dialog", "VirusTotal"))